# Generated by Django 5.2.6 on 2025-10-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='citations',
            field=models.JSONField(default=True),
        ),
    ]
