# Generated by Django 5.2.6 on 2025-10-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chat_citations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='citations',
            field=models.JSONField(default=list),
        ),
    ]
